steps:
  # Dockerイメージをビルドする
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/xhiqibot', '.']

  # Cloud Runにデプロイする
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'xhiqibot'
      - '--image=gcr.io/$PROJECT_ID/xhiqibot'
      - '--region=asia-northeast1' # あなたのデプロイリージョン
      - '--platform=managed'
      - '--allow-unauthenticated' # 外部からのアクセスを許可
      - '--cpu=1' # CPUコア数
      - '--memory=512Mi' # メモリサイズ (必要に応じて調整)
      - '--timeout=300' # タイムアウトを300秒に設定
      - '--set-env-vars=DISCORD_TOKEN=${_DISCORD_TOKEN},OPENAI_API_KEY=${_OPENAI_API_KEY},OPENAI_PROJECT_ID=${_OPENAI_PROJECT_ID},GUILD_ID=${_GUILD_ID}' # ここに環境変数を追加
      - '--min-instances=1' # 常に1つのインスタンスを起動
      - '--max-instances=1' # 最大インスタンス数
    env:
      - 'CLOUDSDK_CORE_PROJECT=${PROJECT_ID}'
      - 'CLOUDSDK_RUN_REGION=asia-northeast1' # リージョンを環境変数にも設定

# ビルドされたイメージをGoogle Container Registryにプッシュする
images:
  - 'gcr.io/$PROJECT_ID/xhiqibot'

# ビルドのデフォルトのディスクサイズを増やす
options:
  diskSizeGb: '100'
  machineType: 'E2_HIGHCPU_8' # ビルド用マシンのスペックを上げる
